# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='click',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2016-10-06 5:07:24', max_length=20),
            preserve_default=False,
        ),
    ]
