# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161108_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='click',
            new_name='click_times',
        ),
    ]
