# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161108_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='click_times',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
